ipam:
  image: janslfonden/phpipam
  ports:
   - "80:80"
  links:
   - phpipam-mysql
phpipam-mysql:
  image: mysql:5.6
  environment: 
   - MYSQL_ROOT_PASSWORD=C6yKNTUvBhZrGo
  volumes:
   - /DockerData/phpipam/:/var/lib/mysql
